name: Code Review with LLM

on:
  pull_request:
    branches: [main]

jobs:
  check_code:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Or your preferred Python version

      - name: Install OpenAI
        run: |
          python -m pip install openai

      - name: Look For Changes
        id: files_changed
        run: |
          MERGE_BASE=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          git diff --name-only "$MERGE_BASE" "${{ github.sha }}" -- '*.py' -- '*.js' -- '*.ts' > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
          echo "files<<EOF" >> $GITHUB_OUTPUT
          cat changed_files.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run LLM Code Review
        id: llm_review
        run: |
          echo "${{ steps.files_changed.outputs.files }}" | while IFS= read -r file; do
            echo "--- Reviewing file: $file ---" >> llm_output.txt
            cat "$file" | python llm.py >> llm_output.txt
            echo "" >> llm_output.txt # Add a newline between reviews
          done
          echo "LLM review complete. Output saved to llm_review_output.txt"
        env:
          OPENAI_API_KEY: ${{ secrets.LLM_API_KEY }}

      - name: Update Pull Request Description
        if: success() || failure() # Update even if the LLM review had issues
        run: |
          PR_BODY=$(gh pr view ${{ github.event.number }} --json body --jq .body)
          LLM_REVIEW_CONTENT=$(cat llm_output.txt)
          echo "$LLM_REVIEW_CONTENT" # debug
          LLM_REVIEW_CONTENT=$(echo "$LLM_REVIEW_CONTENT" | perl -0777 -pe 's#ChatCompletionMessage.*</think>##g') # removes the reasoning section from Nvidia's deepseek-r1 model
          LLM_REVIEW_CONTENT=$(echo "$LLM_REVIEW_CONTENT" | sed "s#\", refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=None, reasoning_content=None)##g") # removes the closure from Nvidia's deepseek-r1 model
          PR_BODY="${PR_BODY}\n\n## LLM Code Review Results\n\n\`\`\`\n${LLM_REVIEW_CONTENT}\n\`\`\`"
          echo -e "$PR_BODY" > updated_pr_body.txt
          gh pr edit ${{ github.event.number }} --body-file updated_pr_body.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
